FROM flink:1.14.4

RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka_2.12/1.14.4/flink-sql-connector-kafka_2.12-1.14.4.jar
RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-avro/1.14.4/flink-avro-1.14.4.jar
RUN wget -P /opt/flink/lib/ https://github.com/knaufk/flink-faker/releases/download/v0.4.0/flink-faker-0.4.0.jar
RUN wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/avro/avro/1.11.0/avro-1.11.0.jar
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.5/jackson-core-2.12.5.jar
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.5/jackson-databind-2.12.5.jar
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.5/jackson-annotations-2.12.5.jar
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-avro-confluent-registry/1.14.4/flink-avro-confluent-registry-1.14.4.jar
RUN wget -P /opt/flink/lib/ https://maven.repository.redhat.com/earlyaccess/all/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar
RUN wget -P /opt/flink/lib/ https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/5.5.2-ccs/kafka-clients-5.5.2-ccs.jar
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-mongodb-cdc/2.2.0/flink-sql-connector-mongodb-cdc-2.2.0.jar
